#!/usr/bin/env bash

dockersock=/var/run/docker.sock
port=2375

{
  while getopts ":p:h" opt; do
    case ${opt} in
      p)
        port=$OPTARG
        ;;
      h)
        echo "dockersocat serves $dockersock on a TCP port, default 2375."
        echo "dockersocat depends on socat."
        echo ""
        echo "Usage:"
        echo "    dockersocat [options]"
        echo ""
        echo "Options:"
        echo "    -p <port>   Serve on 127.0.0.1:<port>."
        echo "    -h          Display this help message."
        exit 1
        ;;
      \?)
        echo "Invalid Option: -$OPTARG"
        exit 1
        ;;
    esac
  done

  echo "Serving $dockersock on 127.0.0.1:$port..."
} 1>&2

socat TCP-L:$port,bind=127.0.0.1,fork,reuseaddr UNIX:/var/run/docker.sock
